Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -51,6 +51,11 @@ jobs:
           rm -f app/google-services.json
           echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json
 
+      - name: Verify google-services.json
+        run: |
+          cat app/google-services.json
+          grep -q '"package_name": "br.com.brunocarvalhs.paguei"' app/google-services.json || (echo "Package name not found in google-services.json" && exit 1)
+
   dependency_check:
     runs-on: ubuntu-latest
     name: Dependency Check
@@ -60,11 +65,14 @@ jobs:
         with:
           ref: ${{ github.ref }}
 
-      - name: OWASP Dependency Check
-        uses: OWASP/dependency-check-action@v2
-        with:
-          project: ${{ github.event.repository.name }}
-          format: 'ALL'
+      - name: Install OWASP Dependency Check
+        run: |
+          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.0/dependency-check-6.5.0-release.zip -o dependency-check.zip
+          unzip dependency-check.zip -d dependency-check
+          export PATH=$PATH:$GITHUB_WORKSPACE/dependency-check/bin
+
+      - name: Run OWASP Dependency Check
+        run: dependency-check.sh --project ${{ github.event.repository.name }} --scan . --format ALL
         continue-on-error: true
 
   license_check:
@@ -83,11 +91,11 @@ jobs:
 
       - name: Run ORT analyze
         run: |
-          ort --info analyze -i . -o ort/analyzer
+          ./oss-review-toolkit/cli/build/install/ort/bin/ort --info analyze -i . -o ort/analyzer
 
       - name: Run ORT evaluate
         run: |
-          ort --info evaluate -i ort/analyzer -o ort/evaluator
+          ./oss-review-toolkit/cli/build/install/ort/bin/ort --info evaluate -i ort/analyzer -o ort/evaluator
 
   unit_tests:
     needs: [setup_environment, create_google_services_file]
@@ -228,16 +236,14 @@ jobs:
           name: ${{ env.APP_NAME }}-AAB-${{ needs.extract_version_and_date.outputs.version }}-${{ needs.extract_version_and_date.outputs.date }}
           path: ./
 
-      - name: Create GitHub Release
+      - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
         with:
           tag_name: ${{ needs.extract_version_and_date.outputs.version }}
-          release_name: ${{ env.APP_NAME }} v${{ needs.extract_version_and_date.outputs.version }}
-          body: |
-            Release of version ${{ needs.extract_version_and_date.outputs.version }} on ${{ needs.extract_version_and_date.outputs.date }}
+          release_name: ${{ env.APP_NAME }} v${{ needs.extract_version_and_date.outputs.version }} on ${{ needs.extract_version_and_date.outputs.date }}
           draft: false
           prerelease: false
 
